### ISSUE TITLE
Are there plans to support with Xiaomi Mix2s？

### ISSUE THREAD

**Issue by chaikefusitu** [Havoc-OS/Havoc-OS.github.io#1]
No offense, I cannot access Telegram channel, so I was wondering if there are plans to support Xiaomi Mix2s.

**Comment by imsuvam** [comment]
Can you share the channel name which you are accessing !

**Comment by chaikefusitu** [comment]
> Can you share the channel name which you are accessing !

All channels, because I can't visit Telegram in my country.
